"""add github to user

Revision ID: d7da44c8e050
Revises: 4d4a28dab48b
Create Date: 2023-08-05 00:41:06.880308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7da44c8e050'
down_revision = '4d4a28dab48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_github_username'), ['github_username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_github_username'))
        batch_op.drop_column('github_username')

    # ### end Alembic commands ###
