"""expand project fields

Revision ID: fc3219d61d02
Revises: 
Create Date: 2023-06-23 19:36:03.344850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc3219d61d02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_constraint('projects_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.drop_column('lead_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_id', mysql.VARCHAR(length=60), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('projects_ibfk_1', 'users', ['lead_id'], ['id'])
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_column('start_date')
        batch_op.drop_column('version')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
